"""
Optional helper: auto-generate a Brawl Stars API key.

Only used when `autogenerateapi: true` is set in configuration.yaml.
Logs into developer.brawlstars.com, revokes stale keys for the same IP,
and creates a fresh key.

WARNING: This uses undocumented internal API endpoints of the developer
portal. It may break at any time if Supercell changes their site.
"""
from __future__ import annotations

import logging
from typing import Any

import aiohttp
import async_timeout

_LOGGER = logging.getLogger(__name__)

_PORTAL_BASE = "https://developer.brawlstars.com/api"
_LOGIN_URL = f"{_PORTAL_BASE}/login"
_KEY_LIST_URL = f"{_PORTAL_BASE}/apikey/list"
_KEY_CREATE_URL = f"{_PORTAL_BASE}/apikey/create"
_KEY_REVOKE_URL = f"{_PORTAL_BASE}/apikey/revoke"

_KEY_NAME = "HomeAssistant-AutoKey"
_KEY_DESC = "Auto-generated by HA Brawl Stats Tracker"


class AutoApiKeyError(Exception):
    """Raised when auto key generation fails."""


async def generate_api_key(
    session: aiohttp.ClientSession,
    email: str,
    password: str,
    external_ip: str,
) -> str:
    """
    Log into the Brawl Stars developer portal and return a valid API key
    whitelisted for *external_ip*.

    Raises AutoApiKeyError on any failure.
    """
    headers = {"Content-Type": "application/json"}

    # 1. Login
    try:
        async with async_timeout.timeout(15):
            async with session.post(
                _LOGIN_URL,
                json={"email": email, "password": password},
                headers=headers,
            ) as resp:
                body: dict[str, Any] = await resp.json()
                if resp.status != 200 or not body.get("status", {}).get("message") == "ok":
                    raise AutoApiKeyError(
                        f"Login failed (HTTP {resp.status}): "
                        f"{body.get('status', {}).get('detail', 'unknown error')}"
                    )
                token: str = body.get("temporaryAPIToken") or body.get("token", "")
                if not token:
                    raise AutoApiKeyError("No token in login response.")
    except (aiohttp.ClientConnectorError, TimeoutError) as err:
        raise AutoApiKeyError(f"Connection error during login: {err}") from err

    auth_headers = {**headers, "Authorization": token}

    # 2. List existing keys
    try:
        async with async_timeout.timeout(15):
            async with session.post(_KEY_LIST_URL, headers=auth_headers, json={}) as resp:
                body = await resp.json()
                existing_keys: list[dict] = body.get("keys") or []
    except Exception as err:
        raise AutoApiKeyError(f"Could not list existing keys: {err}") from err

    # 3. Revoke stale HA keys that are for a different IP or duplicates
    for key in existing_keys:
        if key.get("name") == _KEY_NAME:
            allowed_ips: list[str] = key.get("cidrRanges") or []
            # Revoke if IP doesn't match or we want to refresh
            normalized_ip = f"{external_ip}/32"
            if normalized_ip not in allowed_ips:
                _LOGGER.debug("Revoking stale API key id=%s", key.get("id"))
                try:
                    async with async_timeout.timeout(10):
                        async with session.post(
                            _KEY_REVOKE_URL,
                            headers=auth_headers,
                            json={"id": key["id"]},
                        ):
                            pass
                except Exception:
                    pass  # best-effort
            else:
                # Key already exists for current IP — reuse it
                _LOGGER.info(
                    "Reusing existing API key for IP %s", external_ip
                )
                return key["key"]

    # 4. Create new key
    payload = {
        "name": _KEY_NAME,
        "description": _KEY_DESC,
        "cidrRanges": [f"{external_ip}/32"],
        "scopes": None,
    }
    try:
        async with async_timeout.timeout(15):
            async with session.post(
                _KEY_CREATE_URL, headers=auth_headers, json=payload
            ) as resp:
                body = await resp.json()
                if resp.status != 200:
                    raise AutoApiKeyError(
                        f"Key creation failed (HTTP {resp.status}): "
                        f"{body.get('status', {}).get('detail', 'unknown error')}"
                    )
                new_key: str = (body.get("key") or {}).get("key", "")
                if not new_key:
                    raise AutoApiKeyError("No key value in creation response.")
                _LOGGER.info("Successfully created new Brawl Stars API key.")
                return new_key
    except AutoApiKeyError:
        raise
    except Exception as err:
        raise AutoApiKeyError(f"Key creation request failed: {err}") from err
