"""
Auto-generate a Brawl Stars API key via the developer portal.

Only used when `autogenerateapi: true` is set in configuration.yaml.

API structure is the same across all Supercell developer portals (BrawlStars,
ClashOfClans, ClashRoyale) – verified against multiple open-source wrappers
(coc.py, marsidev/get-sc-key, TheLearneer/supercell-api).

WARNING: Uses undocumented internal Supercell developer portal endpoints.
May break if Supercell changes their backend.
"""
from __future__ import annotations

import logging
from typing import Any

import aiohttp
import async_timeout

_LOGGER = logging.getLogger(__name__)

# All Supercell developer portals share this URL pattern.
# BrawlStars uses developer.brawlstars.com, not developer.brawlstars.com/api/v1
_DEV_BASE = "https://developer.brawlstars.com"
_LOGIN_URL = f"{_DEV_BASE}/api/login"
_KEY_LIST_URL = f"{_DEV_BASE}/api/apikey/list"
_KEY_CREATE_URL = f"{_DEV_BASE}/api/apikey/create"
_KEY_REVOKE_URL = f"{_DEV_BASE}/api/apikey/revoke"

_HA_KEY_NAME = "HomeAssistant-AutoKey"
_HA_KEY_DESC = "Auto-generated by HA Brawl Stats Tracker v2.0"


class AutoApiKeyError(Exception):
    """Raised when auto key generation fails."""


async def generate_api_key(
    session: aiohttp.ClientSession,
    email: str,
    password: str,
    external_ip: str,
) -> str:
    """
    Log into the Brawl Stars developer portal and return a valid API key
    whitelisted for *external_ip*.

    Flow:
    1. POST /api/login  → receive temporaryAPIToken
    2. POST /api/apikey/list  → list existing keys
    3. If a key already exists for this IP, return it immediately.
    4. If 10 keys already exist, revoke the oldest HA-generated one.
    5. POST /api/apikey/create  → return new key

    Raises AutoApiKeyError on any failure.
    """
    base_headers = {
        "Content-Type": "application/json",
    }

    # ------------------------------------------------------------------ #
    # Step 1: Login                                                         #
    # ------------------------------------------------------------------ #
    try:
        async with async_timeout.timeout(15):
            async with session.post(
                _LOGIN_URL,
                json={"email": email, "password": password},
                headers=base_headers,
            ) as resp:
                body: dict[str, Any] = await resp.json(content_type=None)

                if resp.status != 200:
                    detail = body.get("description") or body.get("message") or str(resp.status)
                    raise AutoApiKeyError(f"Login failed (HTTP {resp.status}): {detail}")

                # The portal returns the session token as `temporaryAPIToken`
                temp_token: str = body.get("temporaryAPIToken", "")
                if not temp_token:
                    raise AutoApiKeyError(
                        "Login response did not contain 'temporaryAPIToken'. "
                        f"Body keys: {list(body.keys())}"
                    )

                _LOGGER.debug("Brawl Stars developer portal: login successful.")

    except AutoApiKeyError:
        raise
    except aiohttp.ClientConnectorError as err:
        raise AutoApiKeyError(f"Connection error during login: {err}") from err
    except TimeoutError as err:
        raise AutoApiKeyError("Login request timed out.") from err
    except Exception as err:
        raise AutoApiKeyError(f"Unexpected error during login: {err}") from err

    auth_headers = {**base_headers, "authorization": temp_token}

    # ------------------------------------------------------------------ #
    # Step 2: List existing keys                                           #
    # ------------------------------------------------------------------ #
    try:
        async with async_timeout.timeout(15):
            async with session.post(
                _KEY_LIST_URL,
                headers=auth_headers,
                json={},
            ) as resp:
                body = await resp.json(content_type=None)
                if resp.status != 200:
                    raise AutoApiKeyError(
                        f"Could not list API keys (HTTP {resp.status})."
                    )
                existing_keys: list[dict] = body.get("keys") or []

    except AutoApiKeyError:
        raise
    except Exception as err:
        raise AutoApiKeyError(f"Error listing existing keys: {err}") from err

    # ------------------------------------------------------------------ #
    # Step 3: Check whether a key for our IP already exists                #
    # ------------------------------------------------------------------ #
    normalized_ip = f"{external_ip}/32"

    for key in existing_keys:
        allowed_cidrs: list[str] = key.get("cidrRanges") or []
        # Accept both "x.x.x.x/32" and bare "x.x.x.x"
        if normalized_ip in allowed_cidrs or external_ip in allowed_cidrs:
            _LOGGER.info(
                "Reusing existing Brawl Stars API key (id=%s) for IP %s.",
                key.get("id"),
                external_ip,
            )
            return key["key"]

    # ------------------------------------------------------------------ #
    # Step 4: If 10 keys exist, revoke the oldest HA-generated one         #
    # ------------------------------------------------------------------ #
    MAX_KEYS = 10
    if len(existing_keys) >= MAX_KEYS:
        # Try to revoke an HA auto-generated key first, else the oldest one
        to_revoke = next(
            (k for k in existing_keys if k.get("name") == _HA_KEY_NAME),
            existing_keys[0],
        )
        _LOGGER.warning(
            "10 API keys already exist. Revoking key id=%s ('%s') to make room.",
            to_revoke.get("id"),
            to_revoke.get("name"),
        )
        try:
            async with async_timeout.timeout(10):
                async with session.post(
                    _KEY_REVOKE_URL,
                    headers=auth_headers,
                    json={"id": to_revoke["id"]},
                ) as resp:
                    if resp.status != 200:
                        _LOGGER.warning(
                            "Revoke returned HTTP %s – continuing anyway.", resp.status
                        )
        except Exception as err:
            _LOGGER.warning("Could not revoke key: %s – continuing.", err)

    # ------------------------------------------------------------------ #
    # Step 5: Create a new key                                             #
    # ------------------------------------------------------------------ #
    create_payload = {
        "name": _HA_KEY_NAME,
        "description": _HA_KEY_DESC,
        "cidrRanges": [normalized_ip],
        "scopes": ["clash"],
    }
    try:
        async with async_timeout.timeout(15):
            async with session.post(
                _KEY_CREATE_URL,
                headers=auth_headers,
                json=create_payload,
            ) as resp:
                body = await resp.json(content_type=None)
                if resp.status != 200:
                    detail = body.get("description") or body.get("message") or str(resp.status)
                    raise AutoApiKeyError(
                        f"Key creation failed (HTTP {resp.status}): {detail}"
                    )

                # Response structure: {"key": {"id": "...", "key": "<token>", ...}}
                key_obj: dict = body.get("key") or {}
                new_key: str = key_obj.get("key", "")

                if not new_key:
                    raise AutoApiKeyError(
                        f"Key creation response did not contain key value. Body: {body}"
                    )

                _LOGGER.info(
                    "Successfully created new Brawl Stars API key for IP %s.",
                    external_ip,
                )
                return new_key

    except AutoApiKeyError:
        raise
    except Exception as err:
        raise AutoApiKeyError(f"Key creation request failed: {err}") from err
